var UNITS = {
    bg_base: {
        name: "Simple virus",
        icon: "../img/missing.png",
        sprite: "../img/missing.png",
        life: 10,
        attack: 8,
        defense: 4,
        skills: [],
        bonus: {},
        flying: false,
        rangeAttack: false,
    },
    gg_base: {
        name: "Simple virus",
        icon: "../img/worm.png",
        sprite: "../img/worm_large.png",
        life: 11,
        attack: 7,
        defense: 4,
        skills: [],
        bonus: {},
        flying: false,
        rangeAttack: true,
    },
    gg_healer: {
        name: "Backup",
        icon: "../img/missing.png",
        sprite: "../img/missing.png",
        life: 8,
        attack: 3,
        defense: 5,
        skills: ["healing"],
        bonus: {},
        flying: false,
        rangeAttack: false,
    },
};
